# Generated by Django 5.0.3 on 2024-04-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Electro', 'Electrodomésticos'), ('Ropa', 'Ropa'), ('Alimentos', 'Alimentos'), ('Juguetes', 'Juguetes'), ('Bebidas', 'Bebidas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='tipo_de_sucursal',
            field=models.CharField(choices=[('Hipermercado', 'Hipermercado'), ('Supermercado', 'Supermercado'), ('Maximercado', 'Maximercado'), ('Minimercado', 'Minimercado')], max_length=20),
        ),
    ]
